export const businessTemplates = [
  {
    id: 'wellness',
    name: '养生馆',
    industryType: '养生馆',
    icon: 'leaf',
    fontClass: 'font-sans',
    background: 'from-[#f3dfc2] via-[#fff6e8] to-[#cfe7d8]',
    primaryColor: '#047857',
    buttonColor: '#047857',
    accentColor: '#b9894b',
    priceStyle: 'dark',
    imageStyle: '自然养生风',
    imageKeywords: 'SPA、绿植、蜡烛、按摩、草本、放松',
    defaults: {
      storeName: '云舒养生馆',
      headline: '给疲惫身体一次深度放松',
      subheadline: '专业手法搭配舒缓环境，从肩颈到全身，帮你卸下疲惫，找回轻松状态。',
      services: ['肩颈舒缓护理', '全身经络放松', '草本热敷调理'],
      price: '68 元 / 次',
    },
  },
  {
    id: 'beauty',
    name: '美容院',
    industryType: '美容店',
    icon: 'sparkles',
    fontClass: 'font-sans',
    background: 'from-[#ffe0ea] via-[#fff7fb] to-[#ead8ff]',
    primaryColor: '#be185d',
    buttonColor: '#db2777',
    accentColor: '#f0a3bd',
    priceStyle: 'soft',
    imageStyle: '高级轻奢风',
    imageKeywords: '美容、护肤、镜面、花瓣、轻奢、精致',
    defaults: {
      storeName: '初颜美容院',
      headline: '让肌肤找回细腻光泽',
      subheadline: '温和护理搭配专业流程，适合想改善状态、提升气色的你。',
      services: ['补水亮肤护理', '面部舒缓管理', '精致眉眼服务'],
      price: '98 元 / 次',
    },
  },
  {
    id: 'massage',
    name: '按摩馆',
    industryType: '按摩店',
    icon: 'hand',
    fontClass: 'font-sans',
    background: 'from-[#ead6be] via-[#fff7ed] to-[#dbc7aa]',
    primaryColor: '#92400e',
    buttonColor: '#92400e',
    accentColor: '#d8a15d',
    priceStyle: 'warm',
    imageStyle: '温馨生活风',
    imageKeywords: '按摩、精油、暖光、肩颈、放松、疗愈感',
    defaults: {
      storeName: '松野按摩馆',
      headline: '把紧绷和疲惫慢慢松开',
      subheadline: '从肩颈到腰背，专注舒适体验，让身体重新轻盈起来。',
      services: ['肩颈放松', '腰背舒缓', '精油护理'],
      price: '88 元 / 次',
    },
  },
  {
    id: 'sand',
    name: '沙疗馆',
    industryType: '沙疗馆',
    icon: 'sun',
    fontClass: 'font-sans',
    background: 'from-[#f5d7a1] via-[#fff2d6] to-[#d8b16b]',
    primaryColor: '#a16207',
    buttonColor: '#b45309',
    accentColor: '#e8ba62',
    priceStyle: 'gold',
    imageStyle: '国风典雅',
    imageKeywords: '沙疗、暖沙、养生、阳光、放松、温热',
    defaults: {
      storeName: '暖沙沙疗馆',
      headline: '暖沙包裹，身心都放松',
      subheadline: '温热体验搭配安静环境，适合日常养护和疲惫放松。',
      services: ['温热沙疗', '肩颈放松', '草本养护'],
      price: '58 元 / 次',
    },
  },
  {
    id: 'foot',
    name: '足疗馆',
    industryType: '足疗馆',
    icon: 'footprints',
    fontClass: 'font-sans',
    background: 'from-[#d7c3a4] via-[#fff7eb] to-[#bfa27b]',
    primaryColor: '#78350f',
    buttonColor: '#78350f',
    accentColor: '#d5a868',
    priceStyle: 'dark',
    imageStyle: '自然养生风',
    imageKeywords: '足疗、泡脚、木桶、暖光、放松、养生',
    defaults: {
      storeName: '足悦足疗馆',
      headline: '从脚底开始放松全身',
      subheadline: '安静环境和细致服务，适合下班后给自己安排一次休息。',
      services: ['足底舒缓', '热水泡脚', '肩颈加钟'],
      price: '69 元 / 次',
    },
  },
  {
    id: 'coffee',
    name: '咖啡店',
    industryType: '咖啡店',
    icon: 'coffee',
    fontClass: 'font-sans',
    background: 'from-[#d8b08c] via-[#fff6ec] to-[#7c5b44]',
    primaryColor: '#5f3f2b',
    buttonColor: '#6b4423',
    accentColor: '#c89a6b',
    priceStyle: 'warm',
    imageStyle: 'INS简约风',
    imageKeywords: '咖啡、拿铁、木桌、阳光、甜品、生活方式',
    defaults: {
      storeName: '慢日咖啡',
      headline: '一杯咖啡，把时间慢下来',
      subheadline: '精品咖啡、舒适座位和轻松氛围，适合会友、办公和独处。',
      services: ['手冲咖啡', '招牌拿铁', '甜品套餐'],
      price: '29 元 / 套',
    },
  },
  {
    id: 'hotpot',
    name: '火锅店',
    industryType: '火锅店',
    icon: 'flame',
    fontClass: 'font-sans',
    background: 'from-[#ffb4a2] via-[#fff1e8] to-[#c1121f]',
    primaryColor: '#b91c1c',
    buttonColor: '#dc2626',
    accentColor: '#f97316',
    priceStyle: 'hot',
    imageStyle: '温馨生活风',
    imageKeywords: '火锅、牛油锅底、毛肚、聚餐、热气、朋友',
    defaults: {
      storeName: '沸点火锅',
      headline: '热气腾腾，今晚就开涮',
      subheadline: '招牌锅底搭配新鲜菜品，适合朋友聚会和家庭小聚。',
      services: ['招牌牛油锅', '鲜切肉盘', '双人套餐'],
      price: '128 元 / 双人',
    },
  },
  {
    id: 'pet',
    name: '宠物店',
    industryType: '宠物店',
    icon: 'paw',
    fontClass: 'font-sans',
    background: 'from-[#d8f3dc] via-[#fffdf4] to-[#b7e4c7]',
    primaryColor: '#2d6a4f',
    buttonColor: '#40916c',
    accentColor: '#95d5b2',
    priceStyle: 'soft',
    imageStyle: '温馨生活风',
    imageKeywords: '宠物、猫狗、洗护、可爱、温馨、生活',
    defaults: {
      storeName: '萌爪宠物店',
      headline: '给毛孩子一次舒服护理',
      subheadline: '洗护、美容和用品一站式服务，让宠物干净又舒适。',
      services: ['宠物洗护', '造型修剪', '用品选购'],
      price: '79 元起',
    },
  },
  {
    id: 'flower',
    name: '花店',
    industryType: '花店',
    icon: 'flower',
    fontClass: 'font-sans',
    background: 'from-[#ffd6e0] via-[#fff8f3] to-[#cdb4db]',
    primaryColor: '#9d174d',
    buttonColor: '#be185d',
    accentColor: '#f4a7bb',
    priceStyle: 'soft',
    imageStyle: 'INS简约风',
    imageKeywords: '鲜花、花束、礼物、浪漫、生活、节日',
    defaults: {
      storeName: '一束花店',
      headline: '把心意装进一束花里',
      subheadline: '日常花束、节日礼物和开业花篮，帮你把祝福送到位。',
      services: ['日常花束', '节日定制', '同城配送'],
      price: '99 元起',
    },
  },
  {
    id: 'fitness',
    name: '健身房',
    industryType: '健身房',
    icon: 'dumbbell',
    fontClass: 'font-sans',
    background: 'from-[#d9eafd] via-[#f8fbff] to-[#6b7fd7]',
    primaryColor: '#1d4ed8',
    buttonColor: '#2563eb',
    accentColor: '#60a5fa',
    priceStyle: 'dark',
    imageStyle: 'INS简约风',
    imageKeywords: '健身、器械、力量、训练、塑形、活力',
    defaults: {
      storeName: '燃动健身',
      headline: '从今天开始动起来',
      subheadline: '专业器械、私教指导和轻松氛围，适合新手开始规律训练。',
      services: ['新手体验课', '私教指导', '器械训练区'],
      price: '39 元 / 体验',
    },
  },
  {
    id: 'hair',
    name: '理发店',
    industryType: '理发店',
    icon: 'sparkles',
    fontClass: 'font-sans',
    background: 'from-[#dbeafe] via-[#f8fafc] to-[#d1d5db]',
    primaryColor: '#1d4ed8',
    buttonColor: '#2563eb',
    accentColor: '#93c5fd',
    priceStyle: 'dark',
    imageStyle: 'INS简约风',
    imageKeywords: '理发、发型、镜面、简约、高级、年轻',
    defaults: {
      storeName: '青禾理发店',
      headline: '换个发型，换一种状态',
      subheadline: '专业剪裁搭配清爽造型，让日常形象更利落有精神。',
      services: ['男士精剪', '造型护理', '头皮舒缓'],
      price: '39 元 / 次',
    },
  },
  {
    id: 'nail',
    name: '美甲店',
    industryType: '美甲店',
    icon: 'flower',
    fontClass: 'font-sans',
    background: 'from-[#ffe4e6] via-[#fff7f8] to-[#fbcfe8]',
    primaryColor: '#be123c',
    buttonColor: '#e11d48',
    accentColor: '#f9a8d4',
    priceStyle: 'soft',
    imageStyle: '高级轻奢风',
    imageKeywords: '美甲、手部护理、花瓣、精致、轻奢、年轻女性',
    defaults: {
      storeName: '拾光美甲店',
      headline: '让指尖也有好气色',
      subheadline: '精致款式搭配细致护理，适合通勤、约会和日常变美。',
      services: ['日常美甲', '手部护理', '轻奢款式'],
      price: '69 元 / 次',
    },
  },
];

export const getTemplateById = (id) =>
  businessTemplates.find((template) => template.id === id) || businessTemplates[0];
